language: rust
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - g++-4.9
    - cmake
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
os:
    - linux
    - osx
rust:
    - stable
    - beta
install:
    - |
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
          pip install --user travis-cargo codecov
          export PATH=$PATH:$HOME/.local/bin
          export CC=gcc-4.9
          export CXX=g++-4.9
      fi
    - |
      if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
          # Workaround https://github.com/rust-lang/cargo/issues/3366
          brew unlink libtiff jpeg libpng giflib
      fi
script:
    - cargo test
    - ./scripts/build-docs.sh
after_script:
    - |
      if test "${TRAVIS_OS_NAME}" == "linux" && test "${TRAVIS_RUST_VERSION}" == "stable" ; then
          travis-cargo coverage --no-sudo
          codecov --file target/kcov/kcov-merged/cobertura.xml
      fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: gh-pages
  on:
    branch: master
    tags: true
    os: linux
    rust: stable
