language: rust
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - g++-4.9
    - cmake
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
os:
    - linux
    - osx
rust:
    - stable
    - beta
install:
    - export PATH=$PATH:$HOME/.local/bin:$HOME/local/bin
    - |
      if [[ ${TRAVIS_OS_NAME} == 'linux' && ${TRAVIS_RUST_VERSION} == 'stable' ]]; then
          export EXTRA_WORK=true
      else
          export EXTRA_WORK=false
      fi
    - |
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
          export CC=gcc-4.9
          export CXX=g++-4.9
      fi
    # Build and cache kcov
    - |
      if $EXTRA_WORK; then
          if [ -f ~/local/bin/kcov ]; then
              echo "Using cached kcov from ~/local/bin/kcov"
          else
              mkdir -p $HOME/local
              cd $HOME/local
              wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
              tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build
              cmake -DCMAKE_INSTALL_PREFIX=$HOME/local ..
              make install
              cd $TRAVIS_BUILD_DIR
          fi
      fi
    - rm -rf target/debug/deps/chemfiles-*

script:
    - cargo test -- --test-threads=2
    - cargo test --release -- --test-threads=2
    - cargo run -p chemfiles-sys-tests
    - ./scripts/build-docs.sh
    - |
      if $EXTRA_WORK; then
          rm -rf target/kcov
          kcov --include-pattern=$(pwd) --exclude-pattern=target target/kcov target/debug/deps/chemfiles-*
          bash <(curl -s https://codecov.io/bash) -s target/kcov
      fi

deploy:
  # Deploy nighlty doc from master
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: gh-pages
    on:
        branch: master
        condition: $EXTRA_WORK
  # Deploy release doc from tag build
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: gh-pages
    on:
        tags: true
        condition: $EXTRA_WORK

cache:
  cargo: true
  directories:
      - $HOME/local/bin
