language: rust
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - g++-4.9
    - cmake
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
os:
  - linux
  - osx
rust:
    - stable
    - beta
install:
    - |
      if test "${TRAVIS_OS_NAME}" == "linux"; then
          pip install --user travis-cargo codecov
          export PATH=$PATH:$HOME/.local/bin
          export CC=gcc-4.9
          export CXX=g++-4.9
      fi
    - |
      if test "${TRAVIS_OS_NAME}" == "osx"; then
          sudo pip install travis-cargo
      fi
script:
    - travis-cargo build
    - travis-cargo test
after_success:
    - travis-cargo --only stable doc
    - travis-cargo --only stable doc-upload
    - |
      if test "${TRAVIS_OS_NAME}" == "linux" && test "${TRAVIS_RUST_VERSION}" == "stable" ; then
          travis-cargo coverage --no-sudo
          codecov --file target/kcov/kcov-merged/cobertura.xml
      fi
env:
  global:
    secure: "TZjdXPPIpXXM1zF4ajTt5bfp2M8Mebj2efYpwuv9+ZvhQPuR7v61ky9Y5baSNnjcRZGN78XKgOmkjqdboZtQrrVDkEhzxUWs2k/RwKEzilrlkSy/atkh59AF0qcS26zQoYjWWrkbM47te3SkioB7JbtZrmVuFpvorsHiPas7CqwC0Gq8tdT4rjN5Qr0raneWrNQgAv9+A7rCZ0ZIHRyCSFaNmfj1dA2ZgWOl8sOVcddJPZ8GbE3zYfDk0sO+2ITgyS+qgs4bzsNU6xUdCWKdOZjRrOoRkiUwmKIz7R/mS++AStJgXwsz07Jo5CCK0hYfbnI97i7LLVxWKGz917npl5pB/8HXUTQRGHIzOweVeoa0eWmrPwX8e8jTP/XK/X0far3wSkt2LhVnFWuA23lxlH7sL0dHGcyK3JmiYwPva7a1aVbfpHSWRun7fVdVLjI91jkdKVXvuPro/DkB7MO3ApbeMpm0Zf6dWjWuBP7rYSbhDAOYGvQeaNo1jTMLsg1/Cp7jzzoDu6RTRYPD9UVvELrq7rwoBkWsC7UG4UBTPMorAxIH3m5KW5WNGjinYj7F2AgI/wtj58JpIUyYi3b6sGsk99tGoy9ohnyv3Ok9tyzAXoqOYYdMbj7CWXSfZSxxI2WjAuSDyJh5cpGeRnkT7lgyeom2EtABEs+B2RZWIHo="
