[package]
name = "chemfiles"
version = "0.4.0-dev"
authors = ["Guillaume Fraux <guillaume.fraux@ens.fr>"]
documentation = "https://chemfiles.readthedocs.org/"
repository = "https://github.com/chemfiles/chemfiles.rs"
readme = "README.md"
license = "MPL-2.0"

[lib]
name = "chemfiles"
doctest = false

[dependencies]
chemfiles-sys = {path = "chemfiles-sys"}
