[package]
name = "chemfiles"
version = "0.7.0"
authors = ["Guillaume Fraux <guillaume.fraux@ens.fr>"]
documentation = "https://chemfiles.github.io/chemfiles.rs/"
repository = "https://github.com/chemfiles/chemfiles.rs"
homepage = "https://github.com/chemfiles/chemfiles.rs"
description = "Modern library for chemistry trajectories reading and writing"
keywords = ["computational", "theoretical", "chemistry", "file", "trajectory"]
readme = "README.md"
license = "MPL-2.0"

[lib]
name = "chemfiles"

[dependencies]
chemfiles-sys = {path = "chemfiles-sys", version = "0.7.2"}
libc = "0.2"

[workspace]
members = ["chemfiles-sys"]
