[package]
name = "chemharp"
version = "0.3.0"
authors = ["Guillaume Fraux <guillaume.fraux@ens.fr>"]
documentation = "https://chemharp.readthedocs.org/"
repository = "https://github.com/Luthaf/Chemharp.rs"
readme = "README.md"
license = "MPL-2.0"

[lib]
name = "chemharp"
doctest = false

[dependencies]
chemharp-sys = {path = "chemharp-sys"}
