[package]
name = "chemfiles"
version = "0.5.1"
authors = ["Guillaume Fraux <guillaume.fraux@ens.fr>"]
documentation = "https://chemfiles.readthedocs.org/"
repository = "https://github.com/chemfiles/chemfiles.rs"
homepage = "https://github.com/chemfiles/chemfiles.rs"
description = "Rust bindings to the chemfiles library"
readme = "README.md"
license = "MPL-2.0"

[lib]
name = "chemfiles"
doctest = false

[dependencies]
chemfiles-sys = {path = "chemfiles-sys", version = "0.5.0"}
libc = "0.2.7"
lazy_static = "0.1.15"
